### ISSUE TITLE
I has error  with code on zebra ds4208

### ISSUE THREAD

**Issue by ewendeng** [xtrinch/python-zebra-scanner#1]
pi@raspberrypi:~/Python $ sudo chmod 777 /dev/hidraw*
pi@raspberrypi:~/Python $ ls -l /dev/hidraw*
crwxrwxrwx 1 root root 245, 0 Jan  2 15:54 /dev/hidraw0
crwxrwxrwx 1 root root 245, 1 Jan  2 12:43 /dev/hidraw1
crwxrwxrwx 1 root root 245, 2 Jan  2 12:43 /dev/hidraw2
pi@raspberrypi:~/Python $ python3 test.py 
Traceback (most recent call last):
  File "test.py", line 54, in <module>
    (dev, ep) = connect_to_scanner()	
  File "test.py", line 24, in connect_to_scanner
    print(dev.is_kernel_driver_active(0))
  File "/usr/local/lib/python3.7/dist-packages/usb/core.py", line 1061, in is_kernel_driver_active
    self._ctx.managed_open()
  File "/usr/local/lib/python3.7/dist-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/usb/core.py", line 120, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "/usr/local/lib/python3.7/dist-packages/usb/backend/libusb1.py", line 786, in open_device
    return _DeviceHandle(dev)
  File "/usr/local/lib/python3.7/dist-packages/usb/backend/libusb1.py", line 643, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "/usr/local/lib/python3.7/dist-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)
pi@raspberrypi:~/Python $ 

Did you have any suggest ?

**Comment by ewendeng** [comment]
Bus 001 Device 007: ID 05e0:1200 Symbol Technologies Bar Code Scanner
this my barcode information

**Comment by xtrinch** [comment]
Run python with sudo?
